language-elixir:
  - apps/**/*.ex
  - apps/**/*.exs

language-erlang:
  - apps/**/*.erl
  - apps/**/*.hrl
  - apps/**/rebar.config

scope-api:
  - apps/opentelemetry_api/**

scope-sdk:
  - apps/opentelemetry/**

scope-semconv:
  - apps/opentelemetry_semantic_conventions/**

scope-ci:
  - .github/workflows/**
